language: go

before_install:
  - curl -sf https://up.apex.sh/install | sudo sh
  - sudo up upgrade

install:
  - go get -t ./...
  - sudo apt-get install jq -y

script:
  - go test -v ./...

deploy:
  # dev
  - provider: script
    script: cd web && make
    skip_cleanup: true
    on:
      branch: master

env:
  - GO111MODULE=on
