sudo: required
language: go

before_install:
  - curl -sf https://up.apex.sh/install | sudo sh
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws configure set profile.${AWS_PROFILE_DEV}.aws_access_key_id $AWS_ACCOUNT_USER_ID_DEV
  - aws configure set profile.${AWS_PROFILE_DEV}.aws_secret_access_key $AWS_ACCOUNT_SECRET_DEV
  - aws configure set profile.${AWS_PROFILE_DEV}.region $AWS_DEFAULT_REGION

services:
  - docker

install:
  - go get -t ./...
  - sudo apt-get install jq -y

#after_success:
#  - test -n "$TRAVIS_TAG" && docker login -u=uneetci -p="$DOCKER_PASSWORD"

#script:
#  - go test -v ./...

deploy:
  # dev
  - provider: script
    script: cd web && make PROFILE=${AWS_PROFILE_DEV}
    skip_cleanup: true
    on:
      branch: master
  # demo
  - provider: script
    script:
      cd web && AWS_ACCESS_KEY_ID=$AWS_915001051872_ID AWS_SECRET_ACCESS_KEY=$AWS_915001051872_SECRET make demo
    skip_cleanup: true
    on:
      tags: true
  # production
  - provider: script
    script:
      cd web && AWS_ACCESS_KEY_ID=$AWS_192458993663_ID AWS_SECRET_ACCESS_KEY=$AWS_192458993663_SECRET make prod
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

env:
  - GO111MODULE=on
