sudo: required
language: go
go:
- tip
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- curl -sf https://up.apex.sh/install | sudo sh
- sudo up upgrade
install:
- go get -t ./...
script:
- go test -v ./...
deploy:
 # dev
 - provider: script
   script: AWS_PROFILE=uneet-dev AWS_ACCESS_KEY_ID=$AWS_812644853088_ID AWS_SECRET_ACCESS_KEY=$AWS_812644853088_SECRET up
   skip_cleanup: true
   on:
      branch: master
 # demo
 - provider: script
   script: AWS_PROFILE=uneet-demo AWS_ACCESS_KEY_ID=$AWS_915001051872_ID AWS_SECRET_ACCESS_KEY=$AWS_915001051872_SECRET up
   skip_cleanup: true
   on:
      branch: master
 # production
 - provider: script
   script: AWS_PROFILE=uneet-prod AWS_ACCESS_KEY_ID=$AWS_192458993663_ID AWS_SECRET_ACCESS_KEY=$AWS_192458993663_SECRET up
   skip_cleanup: true
   on:
      branch: master
