language: go

before_install:
  - curl -sf https://up.apex.sh/install | sudo sh

install:
  - go get -t ./...
  - sudo apt-get install jq -y

deploy:
  # dev
  - provider: script
    script: cd web && AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_DEV AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_DEV make
    skip_cleanup: true
    on:
      branch: master

env:
  - GO111MODULE=on
